name: CI

on:
    workflow_dispatch:
        inputs:
            isLatestTag:
                description: 'Is this the last tag?'
                required: true
                type: boolean
                default: false

jobs:
    build-and-publish:
        uses: Centro-Estudos-Gerais/global-actions/.github/workflows/publish-app.yaml@master
        secrets:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
            isLatestTag: ${{ inputs.isLatestTag }}