name: Create Release Branch

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Semantic version number (e.g., 0.0.1)'
        required: true
        type: string
jobs:
  create-release-branch:
    uses: Centro-Estudos-Gerais/global-actions/.github/workflows/create-release-branch.yaml@master
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}
  