name: Create Release Tag

on:
    pull_request:
        types: [closed]
        branches: [master]        

jobs:
    create-release-tag:
        uses: Centro-Estudos-Gerais/global-actions/.github/workflows/create-release-tag.yaml@master
        permissions:
            contents: write